"""Le fuzzer installe par empreinte, et la même chose que la CI.

Le fuzzer construit son image dans l'infrastructure d'OSS-Fuzz, loin de
`mise run check`, et il y installait son lecteur YAML avec un
`pip3 install pyyaml==6.0.3`. La version venait du verrou, l'empreinte non.

Épingler par empreinte crée un second verrou, donc une seconde chose qui
dérive. Ces tests portent sur le contrôle qui l'empêche : le cas où le fuzzer
retarde d'une version, celui où les empreintes divergent, celui où il n'y en a
aucune, et le contre-exemple sans lequel les trois passeraient aussi sur une
fonction qui refuserait tout.
"""

from __future__ import annotations

import verrou_fuzz

#: Deux empreintes plausibles, et la troisième qui n'est dans aucun verrou.
A = "sha256:" + "a" * 64
B = "sha256:" + "b" * 64
C = "sha256:" + "c" * 64

DEPOT = f"""\
# This file was autogenerated by uv
pyyaml==6.0.3 \\
    --hash={A} \\
    --hash={B}
    # via mon-projet
ruff==0.14.0 \\
    --hash={C}
"""


def _fuzzer(version: str = "6.0.3", empreintes: tuple[str, ...] = (A, B)) -> str:
    lignes = [f"pyyaml=={version} \\"]
    lignes += [f"    --hash={e} \\" for e in empreintes]
    return "\n".join(lignes).rstrip(" \\") + "\n" if empreintes else f"pyyaml=={version}\n"


def test_un_verrou_qui_concorde_est_accepte() -> None:
    """Le contre-exemple. Sans lui, les tests suivants passeraient aussi sur une
    fonction qui refuserait tout."""
    assert verrou_fuzz.ecarts_de_verrou(_fuzzer(), DEPOT) == []


def test_le_fuzzer_qui_retarde_dune_version_est_refuse() -> None:
    """Le défaut que ce contrôle existe pour attraper.

    `mise run lock` fait monter PyYAML, le verrou du fuzzer garde l'ancien, et
    plus rien ne rougit : le fuzzer continue de trouver des défauts, dans un
    lecteur que le dépôt n'emploie plus.
    """
    ecarts = verrou_fuzz.ecarts_de_verrou(_fuzzer(version="6.0.2"), DEPOT)

    assert len(ecarts) == 1
    assert "6.0.2" in ecarts[0]
    assert "6.0.3" in ecarts[0]


def test_une_empreinte_qui_ne_vient_pas_du_verrou_est_refusee() -> None:
    """Même version, autre octet : c'est précisément ce que l'empreinte dit.

    Une version recopiée juste avec une empreinte fausse installerait autre
    chose que ce que le dépôt tient, et la version seule ne le verrait pas.
    """
    ecarts = verrou_fuzz.ecarts_de_verrou(_fuzzer(empreintes=(A, C)), DEPOT)

    assert len(ecarts) == 1
    assert "empreintes divergent" in ecarts[0]


def test_un_paquet_sans_empreinte_est_refuse() -> None:
    """C'est le défaut d'origine, signalé par Scorecard.

    Une version épinglée dit *quoi*, une empreinte dit *quel octet*.
    """
    ecarts = verrou_fuzz.ecarts_de_verrou(_fuzzer(empreintes=()), DEPOT)

    assert any("sans empreinte" in ecart for ecart in ecarts)


def test_un_verrou_vide_est_refuse() -> None:
    """Zéro paquet examiné est un vert qui ne dit rien."""
    ecarts = verrou_fuzz.ecarts_de_verrou("# rien\n", DEPOT)

    assert any("n'examine rien" in ecart for ecart in ecarts)


def test_une_installation_sans_empreinte_dans_limage_est_refusee() -> None:
    """Le verrou peut rester impeccable pendant qu'un `pip install` écrit à côté
    ramène une dépendance non épinglée."""
    ecarts = verrou_fuzz.ecarts_de_construction(
        '#!/bin/bash -eu\npip3 install --no-cache-dir "$pyyaml"\n'
    )

    assert any("--require-hashes" in ecart for ecart in ecarts)


def test_linstallation_du_depot_est_acceptee() -> None:
    """Le contre-exemple de la garde précédente."""
    assert (
        verrou_fuzz.ecarts_de_construction(
            '#!/bin/bash -eu\npip3 install --no-cache-dir --require-hashes -r "$verrou"\n'
        )
        == []
    )


def test_le_depot_installe_son_fuzzer_par_empreinte() -> None:
    """Ce que le contrôle dit du dépôt aujourd'hui.

    Le seul test du fichier qui le regarde : les autres prouvent que la garde
    sait refuser, celui-ci dit où en est le dépôt.
    """
    assert verrou_fuzz.main() == 0
