# This file is generated. Do not edit manually.
"""Ce qu'un nom permet de retrouver, tel que les contrats le déclarent.

Cette table est dérivée des contrats versionnés, jamais écrite à la main :
une ressource qui cesse d'être listable, ou qui perd son champ `name`, sort
d'ici à la génération suivante plutôt que de rester une promesse.

Contrats lus :

    specs/scaleway/instance.v1.yml
    specs/scaleway/lb.v1.yml
"""

from __future__ import annotations

from .scaleway import Operation, ResourceLookup

#: Les identifiants qu'un nom suffit à retrouver, et comment.
RESOLUTIONS: dict[str, ResourceLookup] = {
    "acl_id": ResourceLookup(
        parameter="acl_id",
        service="lb",
        schema="scaleway.lb.v1.Acl",
        operation=Operation(
            id="ListAcls",
            method="GET",
            path="/lb/v1/zones/{zone}/frontends/{frontend_id}/acls",
            path_params=("zone", "frontend_id"),
            query_params=("order_by", "page", "page_size", "name"),
            payload_field="acls",
            is_list=True,
            page_param="page",
            per_page_param="page_size",
            retry="safe",
        ),
        scope=("frontend_id",),
        filters_by_name=True,
    ),
    "backend_id": ResourceLookup(
        parameter="backend_id",
        service="lb",
        schema="scaleway.lb.v1.Backend",
        operation=Operation(
            id="ListBackends",
            method="GET",
            path="/lb/v1/zones/{zone}/lbs/{lb_id}/backends",
            path_params=("zone", "lb_id"),
            query_params=("name", "order_by", "page", "page_size"),
            payload_field="backends",
            is_list=True,
            page_param="page",
            per_page_param="page_size",
            retry="safe",
        ),
        scope=("lb_id",),
        filters_by_name=True,
    ),
    "certificate_id": ResourceLookup(
        parameter="certificate_id",
        service="lb",
        schema="scaleway.lb.v1.Certificate",
        operation=Operation(
            id="ListCertificates",
            method="GET",
            path="/lb/v1/zones/{zone}/lbs/{lb_id}/certificates",
            path_params=("zone", "lb_id"),
            query_params=("order_by", "page", "page_size", "name"),
            payload_field="certificates",
            is_list=True,
            page_param="page",
            per_page_param="page_size",
            retry="safe",
        ),
        scope=("lb_id",),
        filters_by_name=True,
    ),
    "frontend_id": ResourceLookup(
        parameter="frontend_id",
        service="lb",
        schema="scaleway.lb.v1.Frontend",
        operation=Operation(
            id="ListFrontends",
            method="GET",
            path="/lb/v1/zones/{zone}/lbs/{lb_id}/frontends",
            path_params=("zone", "lb_id"),
            query_params=("name", "order_by", "page", "page_size"),
            payload_field="frontends",
            is_list=True,
            page_param="page",
            per_page_param="page_size",
            retry="safe",
        ),
        scope=("lb_id",),
        filters_by_name=True,
    ),
    "image_id": ResourceLookup(
        parameter="image_id",
        service="instance",
        schema="scaleway.instance.v1.Image",
        operation=Operation(
            id="ListImages",
            method="GET",
            path="/instance/v1/zones/{zone}/images",
            path_params=("zone",),
            query_params=(
                "organization",
                "per_page",
                "page",
                "name",
                "public",
                "arch",
                "project",
                "tags",
            ),
            payload_field="images",
            is_list=True,
            page_param="page",
            per_page_param="per_page",
            retry="safe",
        ),
        scope=(),
        filters_by_name=True,
    ),
    "lb_id": ResourceLookup(
        parameter="lb_id",
        service="lb",
        schema="scaleway.lb.v1.Lb",
        operation=Operation(
            id="ListLbs",
            method="GET",
            path="/lb/v1/zones/{zone}/lbs",
            path_params=("zone",),
            query_params=(
                "name",
                "order_by",
                "page_size",
                "page",
                "organization_id",
                "project_id",
                "tags",
                "lb_ids",
            ),
            payload_field="lbs",
            is_list=True,
            page_param="page",
            per_page_param="page_size",
            retry="safe",
        ),
        scope=(),
        filters_by_name=True,
    ),
    "placement_group_id": ResourceLookup(
        parameter="placement_group_id",
        service="instance",
        schema="scaleway.instance.v1.PlacementGroup",
        operation=Operation(
            id="ListPlacementGroups",
            method="GET",
            path="/instance/v1/zones/{zone}/placement_groups",
            path_params=("zone",),
            query_params=("per_page", "page", "organization", "project", "tags", "name"),
            payload_field="placement_groups",
            is_list=True,
            page_param="page",
            per_page_param="per_page",
            retry="safe",
        ),
        scope=(),
        filters_by_name=True,
    ),
    "security_group_id": ResourceLookup(
        parameter="security_group_id",
        service="instance",
        schema="scaleway.instance.v1.SecurityGroup",
        operation=Operation(
            id="ListSecurityGroups",
            method="GET",
            path="/instance/v1/zones/{zone}/security_groups",
            path_params=("zone",),
            query_params=(
                "name",
                "organization",
                "project",
                "tags",
                "project_default",
                "per_page",
                "page",
            ),
            payload_field="security_groups",
            is_list=True,
            page_param="page",
            per_page_param="per_page",
            retry="safe",
        ),
        scope=(),
        filters_by_name=True,
    ),
    "server_id": ResourceLookup(
        parameter="server_id",
        service="instance",
        schema="scaleway.instance.v1.Server",
        operation=Operation(
            id="ListServers",
            method="GET",
            path="/instance/v1/zones/{zone}/servers",
            path_params=("zone",),
            query_params=(
                "per_page",
                "page",
                "organization",
                "project",
                "name",
                "private_ip",
                "without_ip",
                "with_ip",
                "commercial_type",
                "state",
                "tags",
                "private_network",
                "order",
                "private_networks",
                "private_nic_mac_address",
                "servers",
            ),
            payload_field="servers",
            is_list=True,
            page_param="page",
            per_page_param="per_page",
            retry="safe",
        ),
        scope=(),
        filters_by_name=True,
    ),
    "snapshot_id": ResourceLookup(
        parameter="snapshot_id",
        service="instance",
        schema="scaleway.instance.v1.Snapshot",
        operation=Operation(
            id="ListSnapshots",
            method="GET",
            path="/instance/v1/zones/{zone}/snapshots",
            path_params=("zone",),
            query_params=(
                "organization",
                "project",
                "per_page",
                "page",
                "name",
                "tags",
                "base_volume_id",
            ),
            payload_field="snapshots",
            is_list=True,
            page_param="page",
            per_page_param="per_page",
            retry="safe",
        ),
        scope=(),
        filters_by_name=True,
    ),
    "subscriber_id": ResourceLookup(
        parameter="subscriber_id",
        service="lb",
        schema="scaleway.lb.v1.Subscriber",
        operation=Operation(
            id="ListSubscriber",
            method="GET",
            path="/lb/v1/zones/{zone}/subscribers",
            path_params=("zone",),
            query_params=("order_by", "page", "page_size", "name", "organization_id", "project_id"),
            payload_field="subscribers",
            is_list=True,
            page_param="page",
            per_page_param="page_size",
            retry="safe",
        ),
        scope=(),
        filters_by_name=True,
    ),
    "volume_id": ResourceLookup(
        parameter="volume_id",
        service="instance",
        schema="scaleway.instance.v1.Volume",
        operation=Operation(
            id="ListVolumes",
            method="GET",
            path="/instance/v1/zones/{zone}/volumes",
            path_params=("zone",),
            query_params=(
                "volume_type",
                "per_page",
                "page",
                "organization",
                "project",
                "tags",
                "name",
            ),
            payload_field="volumes",
            is_list=True,
            page_param="page",
            per_page_param="per_page",
            retry="safe",
        ),
        scope=(),
        filters_by_name=True,
    ),
}

#: Ce que les contrats ne permettent pas de résoudre, **avec sa raison**.
#: Le lookup la rend telle quelle : « inconnu » enverrait l'utilisateur
#: chercher une faute de frappe dans un nom qui est correct.
UNRESOLVABLE: dict[str, str] = {
    "ip_id": "Ip ne porte pas de champ name dans le contrat",
    "private_nic_id": "PrivateNIC ne porte pas de champ name dans le contrat",
    "route_id": "Route ne porte pas de champ name dans le contrat",
    "security_group_rule_id": "SecurityGroupRule ne porte pas de champ name dans le contrat",
}
